title: North American GeoGebra Journal
description: An open-access journal for GeoGebra research and teaching

url: "https://geogebrajournal.com"
baseurl: "/website"

markdown: kramdown

theme: null

collections:
  articles:
    output: true
    permalink: /articles/:name/
